import type { Metadata } from "next";
import "./globals.scss";
import Link from "next/link";
import { cookies } from "next/headers";
import ThemeToggle from "../components/ThemeToggle";
import { merriweather, montserrat } from "./font";

export const metadata: Metadata = {
  title: "overreacted",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  return (
    <html
      lang="en"
      data-theme={theme?.value}
      className={merriweather.className}
    >
      <body>
        <nav>
          <Link href="/">
            <h1 className={montserrat.className}>overreacted</h1>
          </Link>
          <ThemeToggle initialValue={theme?.value as "light" | "dark"} />
        </nav>
        {children}
      </body>
    </html>
  );
}
